# Machine-specific -- generated by `nixos-generate-config` on the install
# target and copied in as-is. If you're installing on different hardware,
# regenerate this (`nixos-generate-config --root /mnt`) rather than reusing
# these UUIDs/modules.
{ config, lib, pkgs, modulesPath, ... }:

{

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5aa6b0a8-da1d-423e-bd08-ddbbaa245777";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C6AC-0787";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault true;
}
